//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{


    public partial class Analytics
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.DropDownList ddlProduct;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Literal litTotalRev;
        protected global::System.Web.UI.WebControls.Literal litTotalQty;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblMetric3;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl valMetric3;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl priceCard;
        protected global::System.Web.UI.WebControls.GridView gvBreakdown;
        protected global::System.Web.UI.WebControls.HiddenField hfSalesLabels;
        protected global::System.Web.UI.WebControls.HiddenField hfSalesData;
        protected global::System.Web.UI.WebControls.HiddenField hfPriceLabels;
        protected global::System.Web.UI.WebControls.HiddenField hfPriceData;
    }
}
